# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/qbuki',
                'doc_host': 'https://heyredhat.github.io',
                'git_url': 'https://github.com/heyredhat/qbuki',
                'lib_path': 'qbuki'},
  'syms': {'qbuki.core': {'qbuki.core.foo': ('core.html#foo', 'qbuki/core.py')}}}
